#!/bin/bash
#

rsync -avz --delete --exclude .git --exclude node_modules  --exclude app/node_modules --exclude app/.env.* . map3api@api.map3.xyz:api
ssh map3api@api.map3.xyz /data/map3api/bin/redeploy
